language: python
python: "3.5"
sudo: false
cache: pip
env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py35-django111
  - TOXENV=py34-django20
  - TOXENV=py35-django20
  - TOXENV=py35-django21
  - TOXENV=docs
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox -e $TOXENV
